name: Build & Publish
on:
  push:
    branches:
      - master
jobs:
   main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Set up JDK 14
        uses: actions/setup-java@v1  #使用官方脚本创建java环境
        with:
          java-version: 14

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to Dockhub Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: likeadoge/task-manager
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
          cache: true
